# Default values for argoapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

project: default
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/drdkadtr/gh-action-argocd-app-env
    targetRevision: HEAD
metadata:
  labels: {}
